from tkinter import *
from tkinter import messagebox
from tkinter import ttk
import mysql.connector as sql
root=Tk()
root.title('Registration form')
root.geometry("500x500")
a=sql.connect(host="localhost",user="root",passwd="root",database="tkin");
b=a.cursor()
ee1=StringVar()
ee2=StringVar()
ee3=StringVar()
ee4=StringVar()
ee5=StringVar()
ee6=StringVar()
def f1():
    eee1=ee1.get()
    eee2=ee2.get()
    eee3=ee3.get()
    eee4=ee4.get()
    eee5=ee5.get()
    eee6=ee6.get()
    if(eee1=="" or eee2=="" or eee3=="" or eee4=="" or eee5=="" or eee6==""):
        messagebox.showwarning("info","Please fill all the fields")
    else:
        try:
            val=(eee1,eee2,eee3,eee4,eee5,eee6)
            b.execute("insert into vac values(%s,%s,%s,%s,%s,%s)",val)
            a.commit()
            messagebox.showinfo("info","Successfully inserted!!!")
        except:
            print("Error")

def f2():
    newwindow=Toplevel(root)
    newwindow.title("Status")
    newwindow.geometry("500x500")
    b.execute("select * from vac")
    data=b.fetchall()
    tree=ttk.Treeview(newwindow)
    tree["columns"]=("Column1","Column2","Column3","Column4","Column5","Column6")
    tree.heading("#1",text="firstname")
    tree.heading("#2",text="lastname")
    tree.heading("#3",text="address")
    tree.heading("#4",text="city")
    tree.heading("#5",text="State")
    tree.heading("#6",text="Country")
    for row in data:
        tree.insert("","end",values=row)
    tree.pack()
def f3():
    eee1=ee1.get()
    try:
        val=(eee1)
        b.execute('delete from vac where fname= %s',eee1)
        a.commit()
        messagebox.showinfo("info","Successfully deleted!!")
    except Exception as e:
        print(e)
l1=Label(root,text="Registration form")
l1.place(x=190,y=20)
l1.config(font=('Arial',9))
l2=Label(root,text="First name :")
l2.place(x=40,y=60)
e1=Entry(root,textvariable=ee1)
e1.place(x=120,y=62)
e2=Entry(root,textvariable=ee2)
e2.place(x=120,y=92)
e3=Entry(root,textvariable=ee3)
e3.place(x=120,y=122)
e4=Entry(root,textvariable=ee4)
e4.place(x=120,y=152)
e5=Entry(root,textvariable=ee5)
e5.place(x=120,y=182)
e6=Entry(root,textvariable=ee6)
e6.place(x=120,y=212)
l3=Label(root,text="Last name :")
l3.place(x=40,y=90)
l4=Label(root,text="Address :")
l4.place(x=40,y=120)
l5=Label(root,text="City :")
l5.place(x=40,y=150)
l6=Label(root,text="State :")
l6.place(x=40,y=180)
l7=Label(root,text="Country :")
l7.place(x=40,y=210)
bt1=Button(root,text="Insert",command=f1)
bt1.place(x=200,y=250)
bt2=Button(root,text="View All",command=f2)
bt2.place(x=200,y=300)
bt3=Button(root,text="Delete",command=f3)
bt3.place(x=200,y=350)
root.mainloop()
